### ISSUE TITLE
If instructor has a price above 0 we should display it

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#102]
If an instructor has a price for a class above 0 we should display that price on their profile. If their classes are free we should also say. So it could be:

< instructorname >'s classes < if price above 0 >cost < currency > < price > per class< else>are FREE of charge< end if >

**Comment by krishna-acondy** [comment]
Do we want this text to appear in the description area? If so, it will require the user to click 'Read more' before they can see it.

<img width="1020" alt="Screenshot 2020-04-19 at 11 23 07" src="https://user-images.githubusercontent.com/2980428/79685370-4cfe5980-8230-11ea-82b1-6196d2488573.png">

The other option is to put it in the 'Upcoming classes' section.

**Comment by krishna-acondy** [comment]
I've put it under the Upcoming classes header and made a PR here. https://github.com/Get-Me-Fit/getmefit/pull/119

**Comment by McD** [comment]
Cool that makes sense
