### ISSUE TITLE
Tidy up footer layout on mobile

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#103]
Maybe put over two lines?

![PNG image](https://user-images.githubusercontent.com/202458/79068059-e15e3e80-7cbb-11ea-8089-c924d20232b5.png)

**Comment by krishna-acondy** [comment]
@McD Here's what I've made it look like. Does that seem okay?

**Desktop**
![image](https://user-images.githubusercontent.com/2980428/79069955-0d80bc00-7cca-11ea-956a-bbf7df63eec5.png)

**Slightly smaller screens/tablets**
![image](https://user-images.githubusercontent.com/2980428/79069969-3012d500-7cca-11ea-8fff-2f6a72c3e4cd.png)

**Mobile**
![image](https://user-images.githubusercontent.com/2980428/79069977-4c167680-7cca-11ea-837d-0c30904e06db.png)

**Comment by McD** [comment]
Looks great!
