### ISSUE TITLE
Incomplete Instructor Profiles throwing 404s

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#11]
**Severity**
Highest

**Description**
On the dashboard if you click on an instructor whose profile is not yet completed users sees a 404 error page

**Steps to reproduce**
* Goto homepage
* login as a participant
* On the dashboard page Click on Mark's profile

**Expected**
Incomplete profiles not shown on dashboard or user friendly messaging shown.

**Actual**
users see deadend 404 error page

![Incomplete-Instructor-Profiles-404](https://user-images.githubusercontent.com/15775263/77855916-8f151c00-71eb-11ea-966a-20eefda608fa.PNG)

**Comment by siebevd** [comment]
@akira22098 I'm 99% sure this resolved now, feel free to open again if not!
