### ISSUE TITLE
Update Zoom link on profile info

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#113]
In the pop up text change Zoom.us > zoom.us/profile (and link it)

<img width="527" alt="Screenshot 2020-04-13 at 20 22 55" src="https://user-images.githubusercontent.com/202458/79152778-b4e21980-7dc4-11ea-9d21-955c4bba02fb.png">

**Comment by krishna-acondy** [comment]
Fixed by https://github.com/Get-Me-Fit/getmefit/commit/0d2d230e34660cbf221d19967f91a188cd3a2b70.
![image](https://user-images.githubusercontent.com/2980428/79685875-e24f1d00-8233-11ea-99cd-23c8dfca1a7a.png)
