### ISSUE TITLE
Validate instructor profile social links as full urls

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#115]
On instructor profile settings we should validate social links to make sure they are full urls

https://getmefit.co/profile/settings

**Comment by McD** [comment]
Example errors:
https://getmefit.co/www.instagram.com/chloereynolds95
https://getmefit.co/www.gftcourses.com
https://getmefit.co/Taisisuits1 (instagram attempt)
https://getmefit.co/Taisi%20suits,%20Livingroom%20Fitbess%20Class (facebook attempt)

**Comment by siebevd** [comment]
fixes have been put in place although he urls hat have been saved before will still be wrong (maybe we should just update in the database, what do you think)?
