### ISSUE TITLE
Yes / No labels seem too faint - user had trouble

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#117]
Yes / No labels seem too faint - user had trouble. See video she sent me

https://drive.google.com/file/d/1-Oc31kw6SRh0V1I4l6yUWG6lUs4zatHU/view?usp=sharing

**Comment by krishna-acondy** [comment]
Fixed by https://github.com/Get-Me-Fit/getmefit/commit/60559d6cc325d3b23ccfb2a7b4c3153bb22aa459.

![image](https://user-images.githubusercontent.com/2980428/79684491-b5960800-8229-11ea-9be9-8060812979ae.png)
