### ISSUE TITLE
Can we change avatar default on bannerbear to more neutral intead of Mark?

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#121]
This advert was sent to an instructor but has Mark's face on it
https://images.bannerbear.com/requests/images/000/024/424/jpg/app-bannerbear-com-projects-kvxjyw31dpe1o0gd6p-requests-ndqr2v1knaymepey8epzrowp7-preview.jpg?1587287417

**Comment by siebevd** [comment]
@McD I think the defaults is something you change in the bannerbear UI no? Don't think I have access to the account details
