### ISSUE TITLE
Instructor Profile form - avatar overlapping profile status on mobile

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#13]
**Severity**
High

**Description**
The Profile avatar is overlapping the profile status line (extra info needed / Live) on mobile

**Steps to reproduce**
* Goto homepage on mobile
* register/login as an instructor
* Goto profile form

**Expected**
Profile status should be clearly visible 

**Actual**
Profile status blocked by avatar

![Instructor-Profile-Pic-overlap-status](https://user-images.githubusercontent.com/15775263/77856141-0ac39880-71ed-11ea-8f30-5b02e01e5019.PNG)

**Comment by McD** [comment]
New designs have gone up
