### ISSUE TITLE
Global footer

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#19]
© < current year > Get Me Fit. All rights reserved. Privacy Policy [https://bit.ly/GMF-Privacy] Terms & Conditions [https://bit.ly/GMF-Terms]

< a href="https://www.facebook.com/getmefitco" target="_blank" class="fa fa-facebook" ></a>  
< a href="https://twitter.com/getmefitco" target="_blank" class="fa fa-twitter "></a> 
< a href="https://www.instagram.com/getmefitco" target="_blank" class="fa fa-instagram" ></a>
< a href="https://www.youtube.com/channel/UCwQki6sjmHu6qGdEEJMTWCw" target="_blank" class="fa fa-youtube" ></a>

**Comment by McD** [comment]
Sorry it closed off my html for social links and year

**Comment by lbaldrick** [comment]
adding now
