### ISSUE TITLE
Homepage meta data

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#22]
Meta data
<title>Online Fitness Classes taught by Group Exercise Instructors &amp; PTs using Zoom - Get Me Fit</title>
    	
    	<meta name="description" content="Get Me Fit is a FREE platform for Group Exercise Instructors &amp; Personal Trainers to promote, schedule &amp; sell live online fitness classes using Zoom.">
	
	<meta property="og:title" content="Online Fitness Classes taught by Group Exercise Instructors &amp; PTs using Zoom - Get Me Fit" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://getmefit.co/" />
	**<meta property="og:image" content="see attached" />**
	<meta property="og:site_name" content="getmefit.co" />
	<meta property="og:description" content="Get Me Fit is a FREE platform for Group Exercise Instructors &amp; Personal Trainers to promote, schedule &amp; sell live online fitness classes using Zoom."/>

![gmf-fbshare](https://user-images.githubusercontent.com/202458/78472795-91b7ca00-7733-11ea-8094-b1f6974a13c9.png)

**Comment by lbaldrick** [comment]
@McD Sorry by meta data what do we mean here, do we mean set the title of the page?

**Comment by McD** [comment]
Can we update this meta data to include the image above? Tag says this right now < meta property="og:image" content="see attached" / >
