### ISSUE TITLE
Instructor welcome email

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#23]
When an instructor profile first goes live and bannerbear is created we send them an email

Subject: Congratulations! Your instructor page is live :)
From: Get Me Fit < hello@getmefit.co >
Bcc: mark@getmefit.co

Hi < firstname >,

Welcome to Get Me Fit! Your page is live here https://getmefit.co/< instructorslug > - this is the page to promote to your participants who want to book your classes.

You created your Get Me Fit login using < Google/Facebook/Email & Password >. Here are some quick links to your account:

Your profile https://getmefit.co/profile/settings
Your class schedule https://getmefit.co/profile/classes
Your dashboard with class bookings https://getmefit.co/dashboard

We have made a couple of help guides that will be useful:

Running Online Fitness Classes with Zoom - https://bit.ly/GMF-Zoom-Guide 
Instructor Help Guide - https://bit.ly/GMF-Instructor-Help 

Finally, we’ve generated an advert to help you promote your classes. You can download it here < bannerbearimagelink >

Thanks,
Get Me Fit

PS After your class remember to encourage your participants to book again at https://getmefit.co/< instructorslug >
—

https://getmefit.co
https://www.facebook.com/getmefitco
https://twitter.com/getmefitco
https://www.instagram.com/getmefitco

**Comment by siebevd** [comment]
@lbaldrick as a heads up, there is a helper in `utils/sendEmail.js` where you can just duplicate the `sendBookingConfirmation` function to send the email!

**Comment by McD** [comment]
Firing too early eg

Hi Stefan Atanasov,

Welcome to Get Me Fit! Your page is live here https://getmefit.co/undefined - this is the page to promote to your participants who want to book your classes.

You created your Get Me Fit login using . Here are some quick links to your account: 

Your profile https://getmefit.co/profile/settings
Your class schedule https://getmefit.co/profile/classes
Your dashboard with class bookings https://getmefit.co/dashboard 

We have made a couple of help guides that will be useful:

Running Online Fitness Classes with Zoom - https://bit.ly/GMF-Zoom-Guide
Instructor Help Guide - https://bit.ly/GMF-Instructor-Help
Finally, we’ve generated an advert to help you promote your classes. You can download it here Your Advert

Thanks,
Get Me Fit

PS After your class remember to encourage your participants to book again at https://getmefit.co/undefined

**Comment by siebevd** [comment]
ensured that email only gets send once and that the username is set
