### ISSUE TITLE
Facebook login doesn't work

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#25]
The facebook login doesn’t work when I tried to sign up as a participant. It says The identity provider configuration is not found.

**Comment by siebevd** [comment]
@McD I've re-enabled this now, can you test again?

**Comment by McD** [comment]
Its saying App not set up: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

My FB username is mhmcdermott

**Comment by siebevd** [comment]
Ah right yeah, I need a valid Privacy Policy to put the app live

```
You must provide a valid Privacy Policy URL 
```

Which one should I use?

**Comment by McD** [comment]
Cool - use this https://bit.ly/GMF-Privacy

**Comment by siebevd** [comment]
@McD ok, app is live now for facebook, so should be working now?

**Comment by McD** [comment]
Yeah all good!
