### ISSUE TITLE
Meta Data Live Instructor Profile

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#30]
Meta data
<title><instructorname> - <jobtitle> - Online Fitness Classes using Zoom</title>
    	
    	<meta name="description" content="<description>">
	
	<meta property="og:title" content="<instructorname> - <jobtitle> - Online Fitness Classes using Zoom" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://getmefit.co/<slug>" />
	<meta property="og:image" content="<bannerbearlink>" />
	<meta property="og:site_name" content="getmefit.co" />
	<meta property="og:description" content="<description>"/>

**Comment by McD** [comment]
This meta data doesn't show up on the instructor page if you are not logged in https://getmefit.co/mark

**Comment by siebevd** [comment]
Meta data is now added & confirmed in the html on the live link (might still take a bit before facebook starts to notice). 

Share Image has also been added to homepage
