### ISSUE TITLE
Participant booking email

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#33]
Can you review that the booking email works as below?

Subject: You've booked: < classtitle > with < instructorname > - < time > < date >
From: Get Me Fit < hello@getmefit.co >
Reply-to: < instructoremail >

Hi < firstname >,

Thanks for booking: < classtitle > with < instructorname > - < time > < date >
< if price is more than 0 >The price of the class is < currency > < price >< /endif >

To join the class please login into Zoom & use this link:
< zoomlink >

< if any payment info has been filled in >
< instructorname > has included some payment details:
< paymentdetails >
< /endif >

Please remember to add the class to your calendar. If you need to cancel your class please login to your Get Me Fit dashboard. If you need any assistance or tips check out our participant help guide https://bit.ly/GMF-Participant-Help

Thanks,
Get Me Fit

PS If you enjoy the class remember to book again with < instructorname > at https://getmefit.co/< instructorslug >
—

https://getmefit.co
https://www.facebook.com/getmefitco
https://twitter.com/getmefitco
https://www.instagram.com/getmefitco

**Comment by lbaldrick** [comment]
Cant add payment details in as we dont have that yet :)

**Comment by McD** [comment]
Can we space out the email better?

<img width="501" alt="Screenshot 2020-04-08 at 18 17 49" src="https://user-images.githubusercontent.com/202458/78813675-487ea900-79c5-11ea-97cb-1bbdd9467b79.png">

**Comment by McD** [comment]
Also the reply-to as instructor address is not implemented

**Comment by siebevd** [comment]
spacing fixed and reply-to also added
