### ISSUE TITLE
Instructor page timezone

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#38]
Somewhere on the instructor page we need to show the timezone they are teaching in

**Comment by siebevd** [comment]
@McD something like this? 
![image](https://user-images.githubusercontent.com/4704886/78500057-452cb880-774c-11ea-87ce-9496610652e9.png)

**Comment by siebevd** [comment]
maybe Times are in the following timezone: (UTC....

**Comment by McD** [comment]
Yeah perfect

**Comment by akira22098** [comment]
As it's referring to timezone shouldn't we be using GMT rather than UTC? GMT is more recognisable. UTC is very server time nerd speak :D
