### ISSUE TITLE
Participant Registration - Users unable to save profile

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#4]
**Severity**
Highest

**Description**
At the end of the Participant registration path, On clicking save profile there's a console error and profile is not saved.

**Steps to reproduce**
* Goto homepage
* click on Register CTA as a participant
* Complete registration and fill profile name
* Click Save CTA

**Expected**
Users can save profile details

**Actual**
Profiles not saved
<img width="1226" alt="Participants-Unable-Save-Profile" src="https://user-images.githubusercontent.com/15775263/77854501-af8ca880-71e2-11ea-82f8-c6981cb82166.png">

**Comment by McD** [comment]
New version has gone up
