### ISSUE TITLE
Users unable to join class from class start time onwards

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#41]
**Describe the bug**
The class listing disappears from the users dashboard from the second the class is scheduled to start so they wont be able to join if they arrive on time/just a few seconds late.

**To Reproduce**
1. Login as instructor and schedule a class for today, and to start in a few minutes time
2. Logout and log back in as a participant
3. Book the newly created class
4. Go to dashboard to see class showing with zoom link
5. Logout and log back in and return to the dashboard exactly at start time (eg if the class starts at 2:15, return to dashboard at exactly 2:15)

**Expected behavior**
User able to see zoom link and join class 

**Actual behavior**
Users cannot see class listing on dashboard and unable to join class

**Screenshots**

Tested on iOS safari but issue can be reproduced across desktop/mobile

**Additional context**
[Recommendation: show zoom link about 10-15mins prior to start time, and keep class listing showing on dashboard for an hour after start time *BUT* disable zoom link about 5-10 mins after class started, this is for health and safety reasons, and users should see a message like “Class already in progress” instead of the zoom link.]

**Comment by akira22098** [comment]
@McD I'd consider this as a launch blocker. If it's been fixed recently let me know and I can retest and close issue

**Comment by McD** [comment]
This seems to be solved now
