### ISSUE TITLE
Participant can save profile without filling in Yes/No questions

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#48]
**Describe the bug**
Participant can save profile without filling in Yes/No questions and move on. They should only be able to if they answer no to all

**To Reproduce**
https://getmefit.netlify.com/profile/settings
2. Click save profile without answering questions

**Expected behavior**
An error message should show saying - As you answered "yes". You will not be able to participate in Get Me Fit classes at this time.

**Comment by siebevd** [comment]
members will now not be able to reach the dashboard page if they haven't completed the PARQ, they will also be redirected to the settings page if they try to book a class and they haven't completed it yet
