### ISSUE TITLE
Login - Logged in users not redirected back from openid

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#6]
**Severity**
High

**Description**
From the homepage, if there's a previous log in (even if logged out), users are taken to the OpenID account selection page with a console error. On selecting an user on the page, users are redirected back to home.
Tested and reproduced using email login & Google login, affects desktop/mobile.

**Steps to reproduce**
* Goto homepage
* Login to an existing account 
* Logout to return to homepage
* Login again using the same method
* select account on the account selection page

**Expected**
Users have the exact same experience on both logins 

**Actual**
users are sent to the account selection page on 2nd login, and then returned to homepage

<img width="1357" alt="Auth-redirect-failed" src="https://user-images.githubusercontent.com/15775263/77854965-55d9ad80-71e5-11ea-8b7c-bd72f85f29fa.png">

**Comment by siebevd** [comment]
similar to #25 & #24, Should be fixed now
