### ISSUE TITLE
Make buttons sentence case

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#61]
On this page http://getmefit.co/profile/classes make the buttons labels consistent

Save Class
Remove Class
Cancel

<img width="643" alt="Screenshot 2020-04-06 at 21 44 53" src="https://user-images.githubusercontent.com/202458/78603450-11d35200-7850-11ea-89b9-24f114b62e34.png">

**Comment by siebevd** [comment]
fixed!
