### ISSUE TITLE
Participant can use account without answering PARQ questions

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#63]
You should not be able to progress unless you've ticked no to all the questions as a participant http://getmefit.co/profile/settings

**Comment by McD** [comment]
The parq questions used to be remembered and time stamped @siebevd do you know what happened to that function?

**Comment by siebevd** [comment]
@McD hmmm, seems like it's still being timestamped but everytime you save, it also updates the date again. 

Is that the bug you spotted or is that a seperate one?

As a fix we should update line 160 in SettingsMember.jsx and only let that be added to updatedFirebaseInfo if the parq_accepted_on doesn't already exist

```    
if (errs.length < 1) {
      updatedFirebaseInfo["parq_accepted_on"] = new Date().getTime();
    }
```

**Comment by siebevd** [comment]
similar to #48
