### ISSUE TITLE
Participant name doesn't update

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#64]
When I am on this page http://getmefit.co/profile/settings as a participant - I update my name and it doesn't save

**Comment by lbaldrick** [comment]
Cant seem to reproduce

**Comment by siebevd** [comment]
@McD This was actually a bug + also we were using the users Displayname (coming from google) instead of the one they saved!

**Comment by siebevd** [comment]
Fix is being deployed and issue is resolved!
