### ISSUE TITLE
Bug on bookings

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#66]
I've booked into a class on Weds at 8am. On the instructor page it shows up as this

<img width="739" alt="Screenshot 2020-04-06 at 22 52 53" src="https://user-images.githubusercontent.com/202458/78608944-a9896e00-7859-11ea-8c24-77356f56248d.png">

**Comment by lbaldrick** [comment]
Cant seem to be able to reproduce

**Comment by siebevd** [comment]
fix was included in last pull request
