### ISSUE TITLE
Members dashboard - Critical issues

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#68]
**Describe the bug**
1) CRITICAL - The Instructor's timezone is not taken into consideration when showing class start time (ideal world: converted to participant's local time, minimum: show instructor's timezone )
2) UX - Bookings not shown in chronological order. This is lower in priority and more of an UX issue. But will always be good in dashboard view to see what's next.
3) CRITICAL - Only the hour is shown. Participants will need to see the exact start time, currently a 7:30pm class is shown as 7 pm

**To Reproduce**
1. As a participant book a few classes on different dates from an instructor in a different timezone
2. Return to participant's dashboard
3. Check classes ordering
4. Check classes start times (vs Participant's timezone)

**Expected behavior**
Participants should get a clear view of exact class start times in order , ideally in the participant's local time zone

This is applicable to desktop & mobile

<img width="970" alt="Screenshot 2020-04-06 14 13 59" src="https://user-images.githubusercontent.com/15775263/78658506-20f2e800-78c2-11ea-8da3-65ee8d9922e1.png">
<img width="1409" alt="Screenshot 2020-04-06 14 07 59" src="https://user-images.githubusercontent.com/15775263/78658519-23edd880-78c2-11ea-8adb-6383d2798789.png">

**Comment by akira22098** [comment]
sorry this was found yesterday then got swamped at work.. so may not fully reflect on latest version

**Comment by siebevd** [comment]
@akira22098 this should all be resolved now, feel free to open issue again if you find any issues!
