### ISSUE TITLE
Header Bar - Logo Shrunk on Mobile

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#7]
**Severity**
Highest

**Description**
The GMF logo is shrunk on mobile

**Steps to reproduce**
* Goto homepage on mobile
* Login as instructor/participant

**Expected**
GMF logo should be visible

**Actual**
GMF logo bearly visible on mobile

![Header-Logo-Link-wrapping-mobile](https://user-images.githubusercontent.com/15775263/77855438-60497680-71e8-11ea-9835-8e70e3763494.PNG)

**Comment by McD** [comment]
New designs have gone up
