### ISSUE TITLE
Add bug tracker

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#71]
Paste the javascript code below just before closing body tag (</body>) of every page where you wish to collect bug reports.

Get the code here Buglog https://buglog.io/profile/configuration/35PWDPVWD1/installation
login is
mark@markmcdermott.me.uk / rK11lIfNsQCK

**Comment by siebevd** [comment]
@McD @akira22098 this seems to be integrated but it keeps saying 
```
Buglog: verify url
```

Which is why it's not showing up, but the url seems to be correct in the settings, so not really sure what's causing the error :/

**Comment by McD** [comment]
They said this:

We rely on a special referrer attribute which is missing in your server setup (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) and which is turned on by default. 

This is required to make sure that the Widget is only used on the website which you have provided while creating the project.
