### ISSUE TITLE
Recently viewed instructors

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#76]
There is a workflow problem at the moment:

- Instructor promotes their profile on social
- User clicks through and thinks it would be cool to join
- They create a profile, click the PARQ (yes/no) questions
- They go to their dashboard but its empty - how do they get back to the instructor?

Solution:
- When a user hits an instructor page we drop a cookie(?) into localstorage that they have viewed that instructor
- On the dashboard we have a section Recently viewed Instructors and show the links to the profile there like we do with Browse Instructors

**Comment by siebevd** [comment]
Fixed, it will now. show the last ~6 instructors you have viewed in an extra item on your dashboard
