### ISSUE TITLE
Header Bar - Nav links wrapping on mobile

### ISSUE THREAD

**Issue by akira22098** [Get-Me-Fit/getmefit#8]
**Severity**
Medium

**Description**
Each of the header nav links are wrapped on mobile

**Steps to reproduce**
* Goto homepage on mobile
* Login as instructor or participant

**Expected**
Nav links not wrapped 

**Actual**
All nav links wrapped
![Header-Logo-Link-wrapping-mobile](https://user-images.githubusercontent.com/15775263/77855508-ca621b80-71e8-11ea-88be-5809aa1673d4.PNG)

**Comment by McD** [comment]
New designs have gone up
