### ISSUE TITLE
I can still book classes after they have passed

### ISSUE THREAD

**Issue by McD** [Get-Me-Fit/getmefit#80]
This is a screenshot at 4pm on 8 April

<img width="804" alt="Screenshot 2020-04-08 at 15 56 20" src="https://user-images.githubusercontent.com/202458/78799067-97224800-79b1-11ea-80f3-da62da704d55.png">

**Comment by siebevd** [comment]
if a class has passed today it won't show up anymore!

I have also added the same day as today in a week's time, so people can already book the next saturday for example (assuming today is Saturday)
